export default [
  {
    "profile_id": 1,
    "first_name": "John",
    "last_name": "Doe",
    "company": "ABC Corp",
    "position": "Marketing Manager",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "University of California, Berkeley",
    "connections": 500,
    "followers": 1000,
    "posts_per_week": 5
  },
  {
    "profile_id": 2,
    "first_name": "Jane",
    "last_name": "Smith",
    "company": "XYZ Inc",
    "position": "Social Media Specialist",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "New York University",
    "connections": 300,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 3,
    "first_name": "Michael",
    "last_name": "Johnson",
    "company": "123 Company",
    "position": "Digital Marketing Analyst",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Chicago",
    "connections": 400,
    "followers": 1200,
    "posts_per_week": 4
  },
  {
    "profile_id": 4,
    "first_name": "Sarah",
    "last_name": "Williams",
    "company": "ABC Corp",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Oxford",
    "connections": 200,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 5,
    "first_name": "David",
    "last_name": "Brown",
    "company": "XYZ Inc",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Miami",
    "connections": 600,
    "followers": 1500,
    "posts_per_week": 6
  },
  {
    "profile_id": 6,
    "first_name": "Jessica",
    "last_name": "Lee",
    "company": "123 Company",
    "position": "Marketing Coordinator",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of Sydney",
    "connections": 250,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 7,
    "first_name": "Christopher",
    "last_name": "Taylor",
    "company": "ABC Corp",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 450,
    "followers": 1100,
    "posts_per_week": 4
  },
  {
    "profile_id": 8,
    "first_name": "Amy",
    "last_name": "Anderson",
    "company": "XYZ Inc",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "Stanford University",
    "connections": 350,
    "followers": 900,
    "posts_per_week": 3
  },
  {
    "profile_id": 9,
    "first_name": "Matthew",
    "last_name": "Clark",
    "company": "123 Company",
    "position": "Public Relations Specialist",
    "industry": "Advertising & Marketing",
    "location": "Boston, MA, United States",
    "education": "Harvard University",
    "connections": 400,
    "followers": 1000,
    "posts_per_week": 5
  },
  {
    "profile_id": 10,
    "first_name": "Emily",
    "last_name": "Hall",
    "company": "ABC Corp",
    "position": "Digital Marketing Manager",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "Northwestern University",
    "connections": 300,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 11,
    "first_name": "Andrew",
    "last_name": "Young",
    "company": "XYZ Inc",
    "position": "Content Creator",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University College London",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 12,
    "first_name": "Amanda",
    "last_name": "Martin",
    "company": "123 Company",
    "position": "Marketing Analyst",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "Florida State University",
    "connections": 500,
    "followers": 1200,
    "posts_per_week": 4
  },
  {
    "profile_id": 13,
    "first_name": "Jonathan",
    "last_name": "Ross",
    "company": "ABC Corp",
    "position": "Brand Ambassador",
    "industry": "Beauty & Cosmetics",
    "location": "Paris, France",
    "education": "Université Paris-Saclay",
    "connections": 150,
    "followers": 400,
    "posts_per_week": 2
  },
  {
    "profile_id": 14,
    "first_name": "Olivia",
    "last_name": "Turner",
    "company": "XYZ Inc",
    "position": "Market Researcher",
    "industry": "Market Research",
    "location": "Berlin, Germany",
    "education": "Humboldt University of Berlin",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 15,
    "first_name": "Nathan",
    "last_name": "Roberts",
    "company": "123 Company",
    "position": "SEO Specialist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Francisco State University",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 16,
    "first_name": "Lauren",
    "last_name": "Clark",
    "company": "ABC Corp",
    "position": "Advertising Manager",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "Columbia University",
    "connections": 400,
    "followers": 1000,
    "posts_per_week": 4
  },
  {
    "profile_id": 17,
    "first_name": "James",
    "last_name": "White",
    "company": "XYZ Inc",
    "position": "Influencer Marketing Coordinator",
    "industry": "Media & Publishing",
    "location": "Los Angeles, CA, United States",
    "education": "University of Southern California",
    "connections": 350,
    "followers": 900,
    "posts_per_week": 3
  },
  {
    "profile_id": 18,
    "first_name": "Sophia",
    "last_name": "Morgan",
    "company": "123 Company",
    "position": "Content Strategist",
    "industry": "E-commerce",
    "location": "London, United Kingdom",
    "education": "London School of Economics and Political Science",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 19,
    "first_name": "William",
    "last_name": "Anderson",
    "company": "ABC Corp",
    "position": "Marketing Coordinator",
    "industry": "Fashion & Apparel",
    "location": "Paris, France",
    "education": "ESCP Business School",
    "connections": 300,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 20,
    "first_name": "Grace",
    "last_name": "Hughes",
    "company": "XYZ Inc",
    "position": "Social Media Analyst",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Jose State University",
    "connections": 400,
    "followers": 1000,
    "posts_per_week": 4
  },
  {
    "profile_id": 21,
    "first_name": "Ethan",
    "last_name": "Reed",
    "company": "123 Company",
    "position": "Marketing Manager",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Illinois at Urbana-Champaign",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 22,
    "first_name": "Abigail",
    "last_name": "Hall",
    "company": "ABC Corp",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Cambridge",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 23,
    "first_name": "Noah",
    "last_name": "Morris",
    "company": "XYZ Inc",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Florida",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 24,
    "first_name": "Chloe",
    "last_name": "Cook",
    "company": "123 Company",
    "position": "Marketing Specialist",
    "industry": "Advertising & Marketing",
    "location": "Boston, MA, United States",
    "education": "Boston University",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 25,
    "first_name": "Daniel",
    "last_name": "Evans",
    "company": "ABC Corp",
    "position": "Digital Marketing Analyst",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of New South Wales",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 26,
    "first_name": "Ella",
    "last_name": "Collins",
    "company": "XYZ Inc",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 27,
    "first_name": "Aiden",
    "last_name": "Murphy",
    "company": "123 Company",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "University of California, Berkeley",
    "connections": 400,
    "followers": 1000,
    "posts_per_week": 4
  },
  {
    "profile_id": 28,
    "first_name": "Lily",
    "last_name": "Rogers",
    "company": "ABC Corp",
    "position": "Social Media Specialist",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "New York University",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 29,
    "first_name": "Lucas",
    "last_name": "Cooper",
    "company": "XYZ Inc",
    "position": "Marketing Coordinator",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Chicago",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 30,
    "first_name": "Mia",
    "last_name": "Richardson",
    "company": "123 Company",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Oxford",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 31,
    "first_name": "Alexander",
    "last_name": "Martin",
    "company": "ABC Corp",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Miami",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 32,
    "first_name": "Sofia",
    "last_name": "Anderson",
    "company": "XYZ Inc",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "Stanford University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 33,
    "first_name": "Logan",
    "last_name": "Turner",
    "company": "123 Company",
    "position": "Digital Marketing Manager",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of Sydney",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 34,
    "first_name": "Ava",
    "last_name": "Taylor",
    "company": "ABC Corp",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 35,
    "first_name": "Liam",
    "last_name": "Harris",
    "company": "XYZ Inc",
    "position": "Content Creator",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University College London",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 36,
    "first_name": "Charlotte",
    "last_name": "Young",
    "company": "123 Company",
    "position": "Marketing Analyst",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "Florida State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 37,
    "first_name": "Mason",
    "last_name": "Ross",
    "company": "ABC Corp",
    "position": "Brand Ambassador",
    "industry": "Beauty & Cosmetics",
    "location": "Paris, France",
    "education": "Université Paris-Saclay",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 38,
    "first_name": "Amelia",
    "last_name": "Turner",
    "company": "XYZ Inc",
    "position": "Market Researcher",
    "industry": "Market Research",
    "location": "Berlin, Germany",
    "education": "Humboldt University of Berlin",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 39,
    "first_name": "Henry",
    "last_name": "Roberts",
    "company": "123 Company",
    "position": "SEO Specialist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Francisco State University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 40,
    "first_name": "Elizabeth",
    "last_name": "Clark",
    "company": "ABC Corp",
    "position": "Advertising Manager",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "Columbia University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 41,
    "first_name": "Alexander",
    "last_name": "Smith",
    "company": "XYZ Inc",
    "position": "Influencer Marketing Coordinator",
    "industry": "Media & Publishing",
    "location": "Los Angeles, CA, United States",
    "education": "University of Southern California",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 42,
    "first_name": "Victoria",
    "last_name": "Morgan",
    "company": "123 Company",
    "position": "Content Strategist",
    "industry": "E-commerce",
    "location": "London, United Kingdom",
    "education": "London School of Economics and Political Science",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 43,
    "first_name": "William",
    "last_name": "Anderson",
    "company": "ABC Corp",
    "position": "Marketing Coordinator",
    "industry": "Fashion & Apparel",
    "location": "Paris, France",
    "education": "ESCP Business School",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 44,
    "first_name": "Emily",
    "last_name": "Hughes",
    "company": "XYZ Inc",
    "position": "Social Media Analyst",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Jose State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 45,
    "first_name": "James",
    "last_name": "Reed",
    "company": "123 Company",
    "position": "Marketing Manager",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Illinois at Urbana-Champaign",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 46,
    "first_name": "Sophia",
    "last_name": "Hall",
    "company": "ABC Corp",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Cambridge",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 47,
    "first_name": "Benjamin",
    "last_name": "Morris",
    "company": "XYZ Inc",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Florida",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 48,
    "first_name": "Mia",
    "last_name": "Cook",
    "company": "123 Company",
    "position": "Marketing Specialist",
    "industry": "Advertising & Marketing",
    "location": "Boston, MA, United States",
    "education": "Boston University",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 49,
    "first_name": "Ethan",
    "last_name": "Evans",
    "company": "ABC Corp",
    "position": "Digital Marketing Analyst",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of New South Wales",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 50,
    "first_name": "Olivia",
    "last_name": "Collins",
    "company": "XYZ Inc",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 51,
    "first_name": "Liam",
    "last_name": "Murphy",
    "company": "123 Company",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "University of California, Berkeley",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 52,
    "first_name": "Isabella",
    "last_name": "Rogers",
    "company": "ABC Corp",
    "position": "Social Media Specialist",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "New York University",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 53,
    "first_name": "Aiden",
    "last_name": "Cooper",
    "company": "XYZ Inc",
    "position": "Marketing Coordinator",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Chicago",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 54,
    "first_name": "Sophia",
    "last_name": "Richardson",
    "company": "123 Company",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Oxford",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 55,
    "first_name": "Jacob",
    "last_name": "Martin",
    "company": "ABC Corp",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Miami",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 56,
    "first_name": "Olivia",
    "last_name": "Anderson",
    "company": "XYZ Inc",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "Stanford University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 57,
    "first_name": "Ethan",
    "last_name": "Turner",
    "company": "123 Company",
    "position": "Digital Marketing Manager",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of Sydney",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 58,
    "first_name": "Ava",
    "last_name": "Taylor",
    "company": "ABC Corp",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 59,
    "first_name": "Logan",
    "last_name": "Harris",
    "company": "XYZ Inc",
    "position": "Content Creator",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University College London",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 60,
    "first_name": "Isabella",
    "last_name": "Young",
    "company": "123 Company",
    "position": "Marketing Analyst",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "Florida State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 61,
    "first_name": "Noah",
    "last_name": "Ross",
    "company": "ABC Corp",
    "position": "Brand Ambassador",
    "industry": "Beauty & Cosmetics",
    "location": "Paris, France",
    "education": "Université Paris-Saclay",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 62,
    "first_name": "Sophia",
    "last_name": "Turner",
    "company": "XYZ Inc",
    "position": "Market Researcher",
    "industry": "Market Research",
    "location": "Berlin, Germany",
    "education": "Humboldt University of Berlin",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 63,
    "first_name": "Liam",
    "last_name": "Roberts",
    "company": "123 Company",
    "position": "SEO Specialist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Francisco State University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 64,
    "first_name": "Charlotte",
    "last_name": "Clark",
    "company": "ABC Corp",
    "position": "Advertising Manager",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "Columbia University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 65,
    "first_name": "Ethan",
    "last_name": "Smith",
    "company": "XYZ Inc",
    "position": "Influencer Marketing Coordinator",
    "industry": "Media & Publishing",
    "location": "Los Angeles, CA, United States",
    "education": "University of Southern California",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 66,
    "first_name": "Olivia",
    "last_name": "Morgan",
    "company": "123 Company",
    "position": "Content Strategist",
    "industry": "E-commerce",
    "location": "London, United Kingdom",
    "education": "London School of Economics and Political Science",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 67,
    "first_name": "William",
    "last_name": "Anderson",
    "company": "ABC Corp",
    "position": "Marketing Coordinator",
    "industry": "Fashion & Apparel",
    "location": "Paris, France",
    "education": "ESCP Business School",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 68,
    "first_name": "Emily",
    "last_name": "Hughes",
    "company": "XYZ Inc",
    "position": "Social Media Analyst",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Jose State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 69,
    "first_name": "James",
    "last_name": "Reed",
    "company": "123 Company",
    "position": "Marketing Manager",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Illinois at Urbana-Champaign",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 70,
    "first_name": "Sophia",
    "last_name": "Hall",
    "company": "ABC Corp",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Cambridge",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 71,
    "first_name": "Benjamin",
    "last_name": "Morris",
    "company": "XYZ Inc",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Florida",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 72,
    "first_name": "Mia",
    "last_name": "Cook",
    "company": "123 Company",
    "position": "Marketing Specialist",
    "industry": "Advertising & Marketing",
    "location": "Boston, MA, United States",
    "education": "Boston University",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 73,
    "first_name": "Ethan",
    "last_name": "Evans",
    "company": "ABC Corp",
    "position": "Digital Marketing Analyst",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of New South Wales",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 74,
    "first_name": "Olivia",
    "last_name": "Collins",
    "company": "XYZ Inc",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 75,
    "first_name": "Liam",
    "last_name": "Murphy",
    "company": "123 Company",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "University of California, Berkeley",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 76,
    "first_name": "Isabella",
    "last_name": "Rogers",
    "company": "ABC Corp",
    "position": "Social Media Specialist",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "New York University",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 77,
    "first_name": "Aiden",
    "last_name": "Cooper",
    "company": "XYZ Inc",
    "position": "Marketing Coordinator",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Chicago",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 78,
    "first_name": "Sophia",
    "last_name": "Richardson",
    "company": "123 Company",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Oxford",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 79,
    "first_name": "Jacob",
    "last_name": "Martin",
    "company": "ABC Corp",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Miami",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 80,
    "first_name": "Olivia",
    "last_name": "Anderson",
    "company": "XYZ Inc",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "Stanford University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 81,
    "first_name": "Ethan",
    "last_name": "Turner",
    "company": "123 Company",
    "position": "Digital Marketing Manager",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of Sydney",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 82,
    "first_name": "Ava",
    "last_name": "Taylor",
    "company": "ABC Corp",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 83,
    "first_name": "Logan",
    "last_name": "Harris",
    "company": "XYZ Inc",
    "position": "Content Creator",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University College London",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 84,
    "first_name": "Isabella",
    "last_name": "Young",
    "company": "123 Company",
    "position": "Marketing Analyst",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "Florida State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 85,
    "first_name": "Noah",
    "last_name": "Ross",
    "company": "ABC Corp",
    "position": "Brand Ambassador",
    "industry": "Beauty & Cosmetics",
    "location": "Paris, France",
    "education": "Université Paris-Saclay",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 86,
    "first_name": "Sophia",
    "last_name": "Turner",
    "company": "XYZ Inc",
    "position": "Market Researcher",
    "industry": "Market Research",
    "location": "Berlin, Germany",
    "education": "Humboldt University of Berlin",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 87,
    "first_name": "Liam",
    "last_name": "Roberts",
    "company": "123 Company",
    "position": "SEO Specialist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Francisco State University",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 88,
    "first_name": "Charlotte",
    "last_name": "Clark",
    "company": "ABC Corp",
    "position": "Advertising Manager",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "Columbia University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 89,
    "first_name": "Ethan",
    "last_name": "Smith",
    "company": "XYZ Inc",
    "position": "Influencer Marketing Coordinator",
    "industry": "Media & Publishing",
    "location": "Los Angeles, CA, United States",
    "education": "University of Southern California",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 90,
    "first_name": "Olivia",
    "last_name": "Morgan",
    "company": "123 Company",
    "position": "Content Strategist",
    "industry": "E-commerce",
    "location": "London, United Kingdom",
    "education": "London School of Economics and Political Science",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 91,
    "first_name": "William",
    "last_name": "Anderson",
    "company": "ABC Corp",
    "position": "Marketing Coordinator",
    "industry": "Fashion & Apparel",
    "location": "Paris, France",
    "education": "ESCP Business School",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 92,
    "first_name": "Emily",
    "last_name": "Hughes",
    "company": "XYZ Inc",
    "position": "Social Media Analyst",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "San Jose State University",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 93,
    "first_name": "James",
    "last_name": "Reed",
    "company": "123 Company",
    "position": "Marketing Manager",
    "industry": "Consulting",
    "location": "Chicago, IL, United States",
    "education": "University of Illinois at Urbana-Champaign",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 94,
    "first_name": "Sophia",
    "last_name": "Hall",
    "company": "ABC Corp",
    "position": "Content Writer",
    "industry": "Media & Publishing",
    "location": "London, United Kingdom",
    "education": "University of Cambridge",
    "connections": 200,
    "followers": 500,
    "posts_per_week": 2
  },
  {
    "profile_id": 95,
    "first_name": "Benjamin",
    "last_name": "Morris",
    "company": "XYZ Inc",
    "position": "Brand Manager",
    "industry": "Consumer Goods",
    "location": "Miami, FL, United States",
    "education": "University of Florida",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 96,
    "first_name": "Mia",
    "last_name": "Cook",
    "company": "123 Company",
    "position": "Marketing Specialist",
    "industry": "Advertising & Marketing",
    "location": "Boston, MA, United States",
    "education": "Boston University",
    "connections": 350,
    "followers": 800,
    "posts_per_week": 3
  },
  {
    "profile_id": 97,
    "first_name": "Ethan",
    "last_name": "Evans",
    "company": "ABC Corp",
    "position": "Digital Marketing Analyst",
    "industry": "E-commerce",
    "location": "Sydney, Australia",
    "education": "University of New South Wales",
    "connections": 400,
    "followers": 900,
    "posts_per_week": 4
  },
  {
    "profile_id": 98,
    "first_name": "Olivia",
    "last_name": "Collins",
    "company": "XYZ Inc",
    "position": "Social Media Manager",
    "industry": "Fashion & Apparel",
    "location": "Los Angeles, CA, United States",
    "education": "University of California, Los Angeles",
    "connections": 250,
    "followers": 600,
    "posts_per_week": 2
  },
  {
    "profile_id": 99,
    "first_name": "Liam",
    "last_name": "Murphy",
    "company": "123 Company",
    "position": "Marketing Strategist",
    "industry": "Technology",
    "location": "San Francisco, CA, United States",
    "education": "University of California, Berkeley",
    "connections": 300,
    "followers": 700,
    "posts_per_week": 3
  },
  {
    "profile_id": 100,
    "first_name": "Isabella",
    "last_name": "Rogers",
    "company": "ABC Corp",
    "position": "Social Media Specialist",
    "industry": "Advertising & Marketing",
    "location": "New York, NY, United States",
    "education": "New York University",
    "connections": 400,
    "followers": 800,
    "posts_per_week": 3
  }
 ]