apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`code4u2.cloud`)
      services:
        - kind: Service
          name: frontend
          port: 80